name: Build Android eBPF

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.target.goarch }}, ${{ matrix.variant.name }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - goarch: arm64
            compiler: aarch64-linux-android35-clang
          - goarch: arm
            goarm: "7"
            compiler: armv7a-linux-androideabi35-clang
          - goarch: amd64
            compiler: x86_64-linux-android35-clang
          - goarch: "386"
            compiler: i686-linux-android35-clang
        variant:
          - name: release
            artifact_suffix: with-ebpf
            extra_tags: ""
          - name: debug
            artifact_suffix: with-ebpf-debug
            extra_tags: ",ebpf_debug"
    env:
      BASE_TAGS: with_gvisor,with_quic,with_dhcp,with_utls,with_clash_api,with_ebpf,badlinkname,tfogo_checklinkname0
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: 1.26.7

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779 # v1
        with:
          ndk-version: r29

      - name: Build
        env:
          CGO_ENABLED: "1"
          GOOS: android
          GOARCH: ${{ matrix.target.goarch }}
          GOARM: ${{ matrix.target.goarm }}
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          CC: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.target.compiler }}
        run: |
          export TAGS="${BASE_TAGS}${{ matrix.variant.extra_tags }}"
          make build

      - name: Upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: sing-box-android-${{ matrix.target.goarch }}-${{ matrix.variant.artifact_suffix }}
          path: sing-box
